name: Validate

on: [push]

jobs:
  pylint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pylint requests click setuptools

      - name: Analysing the code with pylint
        run: |
          pylint $(git ls-files '*.py')

  rpmlint:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    container:
      image: registry.fedoraproject.org/fedora:40
      env:
        NODE_ENV: development
      volumes:
        - ${{ github.workspace }}:/root
      options: --cpus 1 --user 0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          dnf install -y rpmlint

      - name: Run rpmlint
        run: |
          rpmlint /root/package.spec
